### ISSUE TITLE
about the gpu device and training

### ISSUE THREAD

**Issue by lai-pf** [unknownue/puflow#2]
It seems that PUFlow is better than previous work. I want to know the GPU used in this paper and about all the training time.
thanks again, I note that PDFlow is also your work, and thanks for your reply in My PDFlow issue yesterday.

**Comment by unknownue** [comment]
This work is also trained on an RTX3080 card.
For the discrete model, we trained on each dataset for about 12-16 hours.
For the continuous model, it is hard to tell when the model is converged. But for the specific model we provided in this repo, it took about 3-4 days in practice.
